// Traduções de frases das telas internas (chave = texto em português).
// Formato: [pt, en, es]
export const PHRASES: [string, string, string][] = [
  // comuns
  ["Salvar", "Save", "Guardar"], ["Salvo", "Saved", "Guardado"], ["Cancelar", "Cancel", "Cancelar"], ["Confirmar", "Confirm", "Confirmar"],
  ["Remover", "Remove", "Quitar"], ["Editar", "Edit", "Editar"], ["Adicionar", "Add", "Agregar"], ["Abrir", "Open", "Abrir"], ["Voltar", "Back", "Volver"],
  ["Imprimir", "Print", "Imprimir"], ["PDF", "PDF", "PDF"], ["Etiqueta", "Label", "Etiqueta"], ["Buscar", "Search", "Buscar"], ["Aplicar", "Apply", "Aplicar"],
  ["Erro", "Error", "Error"], ["Falha", "Failed", "Fallo"], ["Erro ao salvar", "Error saving", "Error al guardar"], ["Erro ao excluir", "Error deleting", "Error al eliminar"],
  ["Esta ação não pode ser desfeita.", "This action cannot be undone.", "Esta acción no se puede deshacer."],
  ["Nome", "Name", "Nombre"], ["Nome *", "Name *", "Nombre *"], ["E-mail", "E-mail", "Correo"], ["E-mail *", "E-mail *", "Correo *"], ["Senha", "Password", "Contraseña"],
  ["Telefone", "Phone", "Teléfono"], ["Empresa", "Company", "Empresa"], ["Endereço", "Address", "Dirección"], ["Cidade", "City", "Ciudad"], ["Cliente", "Client", "Cliente"],
  ["Status", "Status", "Estado"], ["Tipo", "Type", "Tipo"], ["Observações", "Notes", "Observaciones"], ["Descrição", "Description", "Descripción"], ["Detalhes", "Details", "Detalles"],
  ["Filtros", "Filters", "Filtros"], ["Formato", "Format", "Formato"], ["Modo", "Mode", "Modo"], ["Imagem", "Image", "Imagen"], ["Desenho", "Drawing", "Dibujo"],
  ["Usuário", "User", "Usuario"], ["Sair", "Sign out", "Salir"], ["Verificar", "Check", "Verificar"], ["Gerar", "Generate", "Generar"], ["Registrar", "Register", "Registrar"],
  ["Data e hora", "Date and time", "Fecha y hora"], ["dd/mm/aaaa", "dd/mm/yyyy", "dd/mm/aaaa"], ["dd/mm/aaaa hh:mm", "dd/mm/yyyy hh:mm", "dd/mm/aaaa hh:mm"],
  ["De (dd/mm/aaaa)", "From (dd/mm/yyyy)", "Desde (dd/mm/aaaa)"], ["Até (dd/mm/aaaa)", "To (dd/mm/yyyy)", "Hasta (dd/mm/aaaa)"],
  ["Todos", "All", "Todos"], ["Todos os clientes", "All clients", "Todos los clientes"], ["Todos os tipos", "All types", "Todos los tipos"],
  ["Permissão necessária", "Permission required", "Permiso necesario"], ["Abrir configurações", "Open settings", "Abrir configuración"],
  ["Falha no upload", "Upload failed", "Fallo al subir"], ["Falha ao enviar imagem", "Failed to upload image", "Fallo al enviar imagen"], ["Falha ao gerar PDF", "Failed to generate PDF", "Fallo al generar PDF"],
  ["Nenhum resultado", "No results", "Sin resultados"], ["Selecionar cliente", "Select client", "Seleccionar cliente"], ["Selecione um cliente", "Select a client", "Seleccione un cliente"],
  ["Cadastre um cliente primeiro", "Register a client first", "Registre un cliente primero"], ["Informe o nome", "Enter the name", "Ingrese el nombre"],
  ["Nome é obrigatório", "Name is required", "El nombre es obligatorio"], ["Tirar foto", "Take photo", "Tomar foto"], ["Galeria", "Gallery", "Galería"],
  ["Trocar imagem", "Change image", "Cambiar imagen"], ["Enviar imagem", "Upload image", "Subir imagen"], ["Marca", "Brand", "Marca"], ["Modelo", "Model", "Modelo"],
  ["Marca / modelo", "Brand / model", "Marca / modelo"], ["Setor", "Sector", "Sector"], ["Porta", "Port", "Puerto"], ["Portas", "Ports", "Puertos"], ["Localização", "Location", "Ubicación"],
  ["Sistema", "System", "Sistema"], ["Memória", "Memory", "Memoria"], ["Disco", "Disk", "Disco"], ["Função", "Role", "Función"], ["Agente", "Agent", "Agente"],
  ["Preventiva", "Preventive", "Preventiva"], ["Corretiva", "Corrective", "Correctiva"], ["Técnico", "Technician", "Técnico"], ["Periodicidade", "Frequency", "Periodicidad"],
  ["Próxima", "Next", "Próxima"], ["Última realizada", "Last done", "Última realizada"], ["Sem preventiva", "No preventive", "Sin preventiva"],
  ["Venda", "Sale", "Venta"], ["Serviço", "Service", "Servicio"], ["Orçamento", "Quote", "Presupuesto"], ["Subtotal", "Subtotal", "Subtotal"], ["Desconto", "Discount", "Descuento"],
  ["Impostos", "Taxes", "Impuestos"], ["TOTAL", "TOTAL", "TOTAL"], ["Quantidade", "Quantity", "Cantidad"], ["Validade", "Valid until", "Validez"],
  ["Rack", "Rack", "Rack"], ["Topologia", "Topology", "Topología"], ["Planta", "Floor plan", "Plano"], ["Planta baixa", "Floor plan", "Plano de planta"], ["Cômodo", "Room", "Habitación"],
  ["Servidores", "Servers", "Servidores"], ["Assinantes", "Subscribers", "Suscriptores"], ["Relatórios", "Reports", "Informes"], ["Dispositivo", "Device", "Dispositivo"],
  ["Ler QR Code", "Scan QR Code", "Leer código QR"], ["QR", "QR", "QR"], ["Patrimônio", "Asset tag", "Patrimonio"], ["Nº de série", "Serial no.", "Nº de serie"],
  ["Auto", "Auto", "Auto"], ["Conectar", "Connect", "Conectar"], ["Conexão", "Connection", "Conexión"], ["Identificação", "Identification", "Identificación"],
  ["Redefinir senha", "Reset password", "Restablecer contraseña"], ["Nova senha", "New password", "Nueva contraseña"], ["Criar conta", "Create account", "Crear cuenta"],
  ["Bloquear", "Block", "Bloquear"], ["Desbloquear", "Unblock", "Desbloquear"], ["Aprovar 30 dias", "Approve 30 days", "Aprobar 30 días"],
  ["ativo", "active", "activo"], ["sem pagamento", "unpaid", "sin pago"], ["item", "item", "ítem"], ["itens", "items", "ítems"], ["mês", "month", "mes"], ["meses", "months", "meses"],
  ["à vista", "one-time", "pago único"], ["câmera", "camera", "cámara"], ["galeria", "gallery", "galería"],
  // dispositivos
  ["Novo dispositivo", "New device", "Nuevo dispositivo"], ["Excluir dispositivo", "Delete device", "Eliminar dispositivo"], ["Salvar dispositivo", "Save device", "Guardar dispositivo"],
  ["Adicionar dispositivo", "Add device", "Agregar dispositivo"], ["Nenhum dispositivo", "No devices", "Sin dispositivos"], ["TIPO DE DISPOSITIVO", "DEVICE TYPE", "TIPO DE DISPOSITIVO"],
  ["IDENTIFICAÇÃO", "IDENTIFICATION", "IDENTIFICACIÓN"], ["CONFIGURAÇÃO", "CONFIGURATION", "CONFIGURACIÓN"], ["MANUTENÇÃO", "MAINTENANCE", "MANTENIMIENTO"],
  ["MANUTENÇÃO PREVENTIVA", "PREVENTIVE MAINTENANCE", "MANTENIMIENTO PREVENTIVO"], ["EQUIPAMENTO", "EQUIPMENT", "EQUIPO"], ["ESPECIFICAÇÕES TÉCNICAS", "TECHNICAL SPECS", "ESPECIFICACIONES TÉCNICAS"],
  ["Foto do dispositivo no local", "Photo of the device on site", "Foto del dispositivo en el lugar"], ["Nome / identificação *", "Name / identification *", "Nombre / identificación *"],
  ["Informe um nome/identificação", "Enter a name/identification", "Ingrese un nombre/identificación"], ["Se houver", "If any", "Si existe"],
  ["Setor / local onde está alocado", "Sector / location", "Sector / ubicación"], ["Recepção, Financeiro, CPD...", "Reception, Finance, Data center...", "Recepción, Finanzas, CPD..."],
  ["Preencha somente o que souber; campos em branco são permitidos.", "Fill in only what you know; blank fields are allowed.", "Complete solo lo que sepa; se permiten campos vacíos."],
  ["Periodicidade da preventiva", "Preventive frequency", "Periodicidad de la preventiva"], ["Buscar por setor, patrimônio, série, nome...", "Search by sector, asset tag, serial, name...", "Buscar por sector, patrimonio, serie, nombre..."],
  ["Cadastre computadores, notebooks, servidores, impressoras e gere etiquetas com QR Code.", "Register computers, laptops, servers, printers and generate QR Code labels.", "Registre computadoras, notebooks, servidores, impresoras y genere etiquetas con código QR."],
  ["Registrar preventiva", "Log preventive", "Registrar preventiva"], ["Registrar corretiva", "Log corrective", "Registrar correctiva"], ["Preventiva feita", "Preventive done", "Preventiva hecha"],
  ["Remover registro", "Remove record", "Quitar registro"], ["Excluir este registro de manutenção?", "Delete this maintenance record?", "¿Eliminar este registro de mantenimiento?"],
  ["Nenhuma manutenção registrada. Use os botões abaixo para registrar.", "No maintenance logged. Use the buttons below.", "Sin mantenimientos registrados. Use los botones de abajo."],
  ["Nenhuma configuração informada.", "No specs provided.", "Sin configuración informada."], ["O que foi feito", "What was done", "Qué se hizo"],
  ["O que aconteceu / o que foi feito *", "What happened / what was done *", "Qué pasó / qué se hizo *"], ["Descreva o que aconteceu", "Describe what happened", "Describa lo que pasó"],
  ["Limpeza interna completa, troca de pasta térmica...", "Full internal cleaning, thermal paste replacement...", "Limpieza interna completa, cambio de pasta térmica..."],
  ["Fonte queimou; substituída por fonte 500W...", "PSU burned out; replaced with 500W unit...", "Fuente quemada; reemplazada por fuente 500W..."],
  ["Peças substituídas", "Replaced parts", "Piezas reemplazadas"], ["Custo (R$)", "Cost (R$)", "Costo (R$)"], ["Falha ao gerar etiqueta", "Failed to generate label", "Fallo al generar etiqueta"],
  ["QR Code do dispositivo", "Device QR Code", "Código QR del dispositivo"], ["Leia este código pelo app (botão QR na aba Dispositivos) para abrir a ficha e registrar manutenções.", "Scan this code with the app (QR button in Devices) to open the record and log maintenance.", "Lea este código con la app (botón QR en Dispositivos) para abrir la ficha y registrar mantenimientos."],
  ["Leitura de QR Code", "QR Code scan", "Lectura de código QR"], ["Aponte para a etiqueta do dispositivo", "Point at the device label", "Apunte a la etiqueta del dispositivo"],
  ["OU DIGITE O CÓDIGO", "OR TYPE THE CODE", "O ESCRIBA EL CÓDIGO"], ["Patrimônio ou nº de série", "Asset tag or serial no.", "Patrimonio o nº de serie"], ["Permitir câmera", "Allow camera", "Permitir cámara"],
  ["Usamos a câmera apenas para ler a etiqueta do dispositivo e abrir a ficha com o histórico de manutenções.", "We use the camera only to scan the device label and open its maintenance history.", "Usamos la cámara solo para leer la etiqueta del dispositivo y abrir su historial de mantenimientos."],
  // orçamentos
  ["Novo orçamento", "New quote", "Nuevo presupuesto"], ["Excluir orçamento", "Delete quote", "Eliminar presupuesto"], ["Orçamento salvo", "Quote saved", "Presupuesto guardado"],
  ["Nenhum orçamento", "No quotes", "Sin presupuestos"], ["Crie um orçamento de venda ou serviço e exporte em PDF.", "Create a sales or service quote and export to PDF.", "Cree un presupuesto de venta o servicio y expórtelo en PDF."],
  ["Código (ORC-...)", "Code (ORC-...)", "Código (ORC-...)"], ["Novo item", "New item", "Nuevo ítem"], ["Editar item", "Edit item", "Editar ítem"], ["Confirmar item", "Confirm item", "Confirmar ítem"],
  ["Informe a descrição do item", "Enter the item description", "Ingrese la descripción del ítem"], ["Nenhum item. Adicione produtos ou serviços.", "No items. Add products or services.", "Sin ítems. Agregue productos o servicios."],
  ["Desconto (R$)", "Discount (R$)", "Descuento (R$)"], ["Impostos (R$)", "Taxes (R$)", "Impuestos (R$)"], ["Valor unitário (R$)", "Unit price (R$)", "Precio unitario (R$)"],
  ["Detalhes (opcional)", "Details (optional)", "Detalles (opcional)"], ["Marca, modelo, garantia...", "Brand, model, warranty...", "Marca, modelo, garantía..."],
  ["Condições de pagamento, prazo de entrega, garantia...", "Payment terms, delivery time, warranty...", "Condiciones de pago, plazo de entrega, garantía..."],
  ["Switch 48 portas PoE / Instalação de rack", "48-port PoE switch / Rack installation", "Switch 48 puertos PoE / Instalación de rack"],
  // clientes
  ["Novo cliente", "New client", "Nuevo cliente"], ["Excluir cliente", "Delete client", "Eliminar cliente"], ["Salvar cliente", "Save client", "Guardar cliente"], ["Nenhum cliente", "No clients", "Sin clientes"],
  ["Buscar cliente...", "Search client...", "Buscar cliente..."], ["Cadastre clientes para vincular orçamentos, racks e topologias.", "Register clients to link quotes, racks and topologies.", "Registre clientes para vincular presupuestos, racks y topologías."],
  ["Nome do contato ou razão social", "Contact name or company name", "Nombre del contacto o razón social"], ["CNPJ / CPF", "Tax ID", "CUIT / DNI"],
  ["Rua, número, bairro", "Street, number, district", "Calle, número, barrio"], ["Anexar contrato (PDF)", "Attach contract (PDF)", "Adjuntar contrato (PDF)"],
  ["Trocar contrato (PDF)", "Replace contract (PDF)", "Cambiar contrato (PDF)"], ["Falha ao anexar contrato", "Failed to attach contract", "Fallo al adjuntar contrato"],
  // servidores / mapa
  ["Novo servidor", "New server", "Nuevo servidor"], ["Excluir servidor", "Delete server", "Eliminar servidor"], ["Salvar servidor", "Save server", "Guardar servidor"], ["Nenhum servidor", "No servers", "Sin servidores"],
  ["Cadastre servidores com host/porta para monitorar o status no mapa.", "Register servers with host/port to monitor status on the map.", "Registre servidores con host/puerto para monitorear el estado en el mapa."],
  ["Nome e host são obrigatórios", "Name and host are required", "Nombre y host son obligatorios"], ["Host / IP *", "Host / IP *", "Host / IP *"], ["Host / Domínio", "Host / Domain", "Host / Dominio"],
  ["Servidor de arquivos, AD, Firewall, NVR...", "File server, AD, Firewall, NVR...", "Servidor de archivos, AD, Firewall, NVR..."], ["LOCALIZAÇÃO NO MAPA", "MAP LOCATION", "UBICACIÓN EN EL MAPA"],
  ["Ou toque no mapa para ajustar a posição manualmente.", "Or tap the map to adjust the position manually.", "O toque el mapa para ajustar la posición manualmente."],
  ["Escopo / Rede", "Scope / Network", "Alcance / Red"], ["Escopo de rede / observações (sensível)", "Network scope / notes (sensitive)", "Alcance de red / observaciones (sensible)"],
  ["Topologia vinculada", "Linked topology", "Topología vinculada"], ["Agente de monitoramento", "Monitoring agent", "Agente de monitoreo"], ["CHAVE DO AGENTE", "AGENT KEY", "CLAVE DEL AGENTE"],
  ["SCRIPT", "SCRIPT", "SCRIPT"], ["Copiar script", "Copy script", "Copiar script"], ["Script copiado", "Script copied", "Script copiado"], ["Cole no servidor conforme as instruções.", "Paste on the server as instructed.", "Pegue en el servidor según las instrucciones."],
  ["Atualizar status", "Refresh status", "Actualizar estado"], ["CPU · HISTÓRICO", "CPU · HISTORY", "CPU · HISTORIAL"], ["TOQUE PARA REVELAR DADOS DE ACESSO", "TAP TO REVEAL ACCESS DATA", "TOQUE PARA REVELAR DATOS DE ACCESO"],
  ["OCULTAR DADOS SENSÍVEIS", "HIDE SENSITIVE DATA", "OCULTAR DATOS SENSIBLES"], ["Pinça para zoom · verde online · amarelo instável · vermelho offline", "Pinch to zoom · green online · yellow unstable · red offline", "Pinza para zoom · verde en línea · amarillo inestable · rojo fuera de línea"],
  ["Sem dados de CPU/memória/disco. Instale o agente de monitoramento (botão \"Agente\").", "No CPU/memory/disk data. Install the monitoring agent (\"Agent\" button).", "Sin datos de CPU/memoria/disco. Instale el agente de monitoreo (botón \"Agente\")."],
  // racks / topologia / planta
  ["Racks · Topologias · Plantas", "Racks · Topologies · Floor plans", "Racks · Topologías · Planos"], ["Excluir rack", "Delete rack", "Eliminar rack"], ["Configurações do rack", "Rack settings", "Configuración del rack"],
  ["Informe o nome do rack", "Enter the rack name", "Ingrese el nombre del rack"], ["Tamanho (U)", "Size (U)", "Tamaño (U)"], ["Local / Sala", "Location / Room", "Lugar / Sala"], ["Sala técnica", "Technical room", "Sala técnica"],
  ["Rack principal - CPD", "Main rack - Data center", "Rack principal - CPD"], ["1U livre", "1U free", "1U libre"], ["Espaço insuficiente", "Not enough space", "Espacio insuficiente"],
  ["Rack ocupado acima do novo tamanho", "Rack occupied above the new size", "Rack ocupado por encima del nuevo tamaño"], ["Remova os equipamentos das posições superiores antes de reduzir.", "Remove equipment from the upper positions before shrinking.", "Quite los equipos de las posiciones superiores antes de reducir."],
  ["Vincular a servidor monitorado (LED de status)", "Link to monitored server (status LED)", "Vincular a servidor monitoreado (LED de estado)"], ["Modelo, VLANs, observações", "Model, VLANs, notes", "Modelo, VLANs, observaciones"],
  ["Excluir topologia", "Delete topology", "Eliminar topología"], ["Criar topologia", "Create topology", "Crear topología"], ["Informe o nome da topologia", "Enter the topology name", "Ingrese el nombre de la topología"],
  ["Canvas vazio", "Empty canvas", "Lienzo vacío"], ["Adicione dispositivos ou gere a topologia automaticamente.", "Add devices or generate the topology automatically.", "Agregue dispositivos o genere la topología automáticamente."],
  ["Gerar topologia automaticamente", "Generate topology automatically", "Generar topología automáticamente"], ["Atenção: o diagrama atual será substituído.", "Warning: the current diagram will be replaced.", "Atención: el diagrama actual será reemplazado."],
  ["Informe a quantidade de equipamentos. A topologia será gerada em estrela (roteador → switches → dispositivos finais) e poderá ser ajustada manualmente.", "Enter the number of devices. A star topology will be generated (router → switches → end devices) and can be adjusted manually.", "Ingrese la cantidad de equipos. Se generará una topología en estrella (router → switches → dispositivos finales) que podrá ajustarse manualmente."],
  ["Roteadores", "Routers", "Routers"], ["Switches", "Switches", "Switches"], ["Access Points", "Access Points", "Access Points"], ["Computadores", "Computers", "Computadoras"], ["Impressoras", "Printers", "Impresoras"], ["Câmeras", "Cameras", "Cámaras"],
  ["Incluir Internet / WAN", "Include Internet / WAN", "Incluir Internet / WAN"], ["Toque no dispositivo de destino para conectar", "Tap the target device to connect", "Toque el dispositivo de destino para conectar"],
  ["Rótulo (porta / VLAN / cabo)", "Label (port / VLAN / cable)", "Etiqueta (puerto / VLAN / cable)"], ["IP / Rede", "IP / Network", "IP / Red"], ["Sala / Local", "Room / Location", "Sala / Lugar"],
  ["Rede matriz - Térreo", "HQ network - Ground floor", "Red matriz - Planta baja"], ["Escritório - 1º andar", "Office - 1st floor", "Oficina - 1º piso"],
  ["Excluir planta", "Delete floor plan", "Eliminar plano"], ["Informe o nome da planta", "Enter the floor plan name", "Ingrese el nombre del plano"], ["Adicionar ponto", "Add point", "Agregar punto"],
  ["Adicionar cômodo", "Add room", "Agregar habitación"], ["Toque na planta...", "Tap on the plan...", "Toque el plano..."], ["Toque para posicionar...", "Tap to place...", "Toque para posicionar..."],
  ["Envie a imagem da planta baixa", "Upload the floor plan image", "Suba la imagen del plano"], ["Permita o acesso às fotos para enviar a planta. Abrir configurações?", "Allow photo access to upload the plan. Open settings?", "Permita el acceso a las fotos para subir el plano. ¿Abrir configuración?"],
  ["Use \"Adicionar ponto\" e toque no local desejado da planta.", "Use \"Add point\" and tap the desired spot on the plan.", "Use \"Agregar punto\" y toque el lugar deseado del plano."], ["Ponto de rede", "Network point", "Punto de red"],
  ["Posição X (%)", "X position (%)", "Posición X (%)"], ["Posição Y (%)", "Y position (%)", "Posición Y (%)"], ["Largura (%)", "Width (%)", "Ancho (%)"], ["Altura (%)", "Height (%)", "Alto (%)"], ["Altura", "Height", "Alto"],
  ["Sala técnica, 2º andar", "Technical room, 2nd floor", "Sala técnica, 2º piso"],
  // relatórios
  ["Imprimir ou gerar PDF", "Print or generate PDF", "Imprimir o generar PDF"], ["Tipo de ativo", "Asset type", "Tipo de activo"], ["PERÍODO DE CADASTRO", "REGISTRATION PERIOD", "PERÍODO DE REGISTRO"],
  ["PERÍODO DAS MANUTENÇÕES", "MAINTENANCE PERIOD", "PERÍODO DE MANTENIMIENTOS"], ["Falha ao gerar relatório", "Failed to generate report", "Fallo al generar informe"],
  ["Ativos e manutenções", "Assets and maintenance", "Activos y mantenimientos"], ["Completo — com configurações e métricas", "Full — with specs and metrics", "Completo — con configuración y métricas"],
  ["Resumo — uma linha por servidor", "Summary — one line per server", "Resumen — una línea por servidor"],
  ["Relatório de ativos", "Assets report", "Informe de activos"], ["Relatório de servidores", "Servers report", "Informe de servidores"], ["resumo", "summary", "resumen"],
  ["Cadastro", "Registered", "Registro"], ["Manutenções", "Maintenance", "Mantenimientos"], ["todo o período", "entire period", "todo el período"], ["início", "start", "inicio"], ["hoje", "today", "hoy"],
  ["Gerado em", "Generated on", "Generado el"], ["até", "to", "hasta"], ["servidor(es)", "server(s)", "servidor(es)"], ["Etiqueta", "Label", "Etiqueta"], ["Impresso em", "Printed on", "Impreso el"], ["SEM PATRIMÔNIO", "NO ASSET TAG", "SIN PATRIMONIO"], ["Setor:", "Sector:", "Sector:"], ["Ativos", "Assets", "Activos"], ["Preventivas", "Preventive", "Preventivas"], ["Corretivas", "Corrective", "Correctivas"], ["Custo total", "Total cost", "Costo total"],
  ["Prev. vencidas", "Overdue prev.", "Prev. vencidas"], ["Prev. próximas", "Upcoming prev.", "Prev. próximas"], ["Totais por tipo e status", "Totals by type and status", "Totales por tipo y estado"],
  ["Qtd", "Qty", "Cant."], ["Patrimônio / Série", "Asset tag / Serial", "Patrimonio / Serie"], ["Setor / Cliente", "Sector / Client", "Sector / Cliente"], ["Manut.", "Maint.", "Mant."],
  ["Nenhum ativo no filtro", "No assets match the filter", "Ningún activo en el filtro"], ["Manutenções no período", "Maintenance in period", "Mantenimientos en el período"],
  ["Nenhuma manutenção no período", "No maintenance in period", "Sin mantenimientos en el período"], ["Data", "Date", "Fecha"], ["Custo", "Cost", "Costo"], ["Peças", "Parts", "Piezas"],
  ["Documento gerado eletronicamente", "Electronically generated document", "Documento generado electrónicamente"], ["Total", "Total", "Total"], ["Online", "Online", "En línea"], ["Offline", "Offline", "Fuera de línea"],
  ["Servidor", "Server", "Servidor"], ["Cidade/UF", "City/State", "Ciudad/Prov."], ["S.O.", "OS", "S.O."], ["Última verificação", "Last check", "Última verificación"], ["Sem verificação", "Not checked", "Sin verificación"],
  ["Local", "Location", "Lugar"], ["Uso CPU", "CPU usage", "Uso CPU"], ["Uso memória", "Memory usage", "Uso memoria"], ["Uso disco", "Disk usage", "Uso disco"],
  ["Agente de monitoramento não instalado", "Monitoring agent not installed", "Agente de monitoreo no instalado"], ["próx.", "next", "próx."],
  ["Orçamento comercial", "Commercial quote", "Presupuesto comercial"], ["ORÇAMENTO", "QUOTE", "PRESUPUESTO"], ["Prestação de serviços", "Services", "Prestación de servicios"], ["Venda de produtos", "Product sale", "Venta de productos"],
  ["Emitido em", "Issued on", "Emitido el"], ["Válido até", "Valid until", "Válido hasta"], ["Documento:", "Document:", "Documento:"], ["Itens", "Items", "Ítems"], ["Unitário", "Unit", "Unitario"], ["Sem itens", "No items", "Sin ítems"],
  ["Impostos / taxas", "Taxes / fees", "Impuestos / tasas"], ["Rascunho", "Draft", "Borrador"], ["Pendente", "Pending", "Pendiente"], ["Pendente de aprovação", "Pending approval", "Pendiente de aprobación"],
  ["Aprovado", "Approved", "Aprobado"], ["Rejeitado", "Rejected", "Rechazado"], ["Concluído", "Completed", "Concluido"],
  // opções / constantes
  ["Ativo", "Active", "Activo"], ["Em manutenção", "Under maintenance", "En mantenimiento"], ["Reserva / estoque", "Spare / stock", "Reserva / stock"], ["Baixado", "Retired", "Dado de baja"],
  ["Computador", "Computer", "Computadora"], ["Notebook", "Laptop", "Notebook"], ["Tablet", "Tablet", "Tablet"], ["Impressora", "Printer", "Impresora"], ["Celular", "Phone", "Celular"],
  ["Equipamento de rede", "Network equipment", "Equipo de red"], ["Outro", "Other", "Otro"], ["Vencidas", "Overdue", "Vencidas"], ["Próximas", "Upcoming", "Próximas"],
  ["Ponto de rede (RJ45)", "Network point (RJ45)", "Punto de red (RJ45)"], ["Access Point", "Access Point", "Access Point"], ["Câmera", "Camera", "Cámara"], ["Tomada elétrica", "Power outlet", "Toma eléctrica"],
  ["Processador", "Processor", "Procesador"], ["Memória (qtd)", "Memory (size)", "Memoria (cant.)"], ["Memória (modelo)", "Memory (model)", "Memoria (modelo)"], ["Memória (marca)", "Memory (brand)", "Memoria (marca)"],
  ["HD / SSD", "HD / SSD", "HD / SSD"], ["Placa de vídeo", "Graphics card", "Tarjeta de video"], ["Placa de rede", "Network card", "Tarjeta de red"], ["Placa-mãe", "Motherboard", "Placa madre"],
  ["Monitor", "Monitor", "Monitor"], ["Teclado / Mouse", "Keyboard / Mouse", "Teclado / Mouse"], ["Sistema operacional", "Operating system", "Sistema operativo"],
  // configurações / conta
  ["Alertas por e-mail (SMTP)", "E-mail alerts (SMTP)", "Alertas por correo (SMTP)"], ["Servidor SMTP", "SMTP server", "Servidor SMTP"], ["Remetente", "Sender", "Remitente"],
  ["E-mail que recebe alertas", "Alert recipient e-mail", "Correo que recibe alertas"], ["Alertas ativos", "Alerts enabled", "Alertas activas"], ["Salvar e-mail", "Save e-mail", "Guardar correo"],
  ["Enviar teste", "Send test", "Enviar prueba"], ["E-mail de teste enviado", "Test e-mail sent", "Correo de prueba enviado"], ["Configurações salvas", "Settings saved", "Configuración guardada"],
  ["Envia e-mail quando um servidor ficar offline e um resumo diário das preventivas vencidas/próximas. Ex.: Gmail smtp.gmail.com porta 587 (senha de app); Outlook smtp.office365.com 587; porta 465 usa SSL.", "Sends an e-mail when a server goes offline and a daily digest of overdue/upcoming preventive maintenance. E.g. Gmail smtp.gmail.com port 587 (app password); Outlook smtp.office365.com 587; port 465 uses SSL.", "Envía un correo cuando un servidor queda fuera de línea y un resumen diario de preventivas vencidas/próximas. Ej.: Gmail smtp.gmail.com puerto 587 (contraseña de app); Outlook smtp.office365.com 587; el puerto 465 usa SSL."],
  ["Usuário operador (1 por licença)", "Operator user (1 per license)", "Usuario operador (1 por licencia)"], ["Criar operador", "Create operator", "Crear operador"], ["Usuário operador criado", "Operator user created", "Usuario operador creado"],
  ["O operador pode cadastrar e editar dispositivos, servidores, preventivas e corretivas, mas não pode excluir registros nem alterar configurações.", "The operator can create and edit devices, servers and maintenance, but cannot delete records or change settings.", "El operador puede crear y editar dispositivos, servidores y mantenimientos, pero no puede eliminar registros ni cambiar la configuración."],
  ["Operadores não podem alterar.", "Operators cannot change this.", "Los operadores no pueden cambiarlo."], ["Trocar logo", "Change logo", "Cambiar logo"], ["Enviar logo", "Upload logo", "Subir logo"],
  ["Logo atualizada", "Logo updated", "Logo actualizado"], ["A nova logo aparecerá no app e nos relatórios.", "The new logo will appear in the app and reports.", "El nuevo logo aparecerá en la app y en los informes."],
  ["Falha ao enviar logo", "Failed to upload logo", "Fallo al subir logo"], ["Link do tutorial em PDF", "PDF tutorial link", "Enlace del tutorial en PDF"], ["Link do tutorial em vídeo", "Video tutorial link", "Enlace del tutorial en video"],
  ["Imagem da tela de login (JPG/PNG 1080 × 1600 px, até 2 MB)", "Login screen image (JPG/PNG 1080 × 1600 px, up to 2 MB)", "Imagen de la pantalla de inicio (JPG/PNG 1080 × 1600 px, hasta 2 MB)"],
  ["Imagem da tela de login atualizada", "Login screen image updated", "Imagen de inicio actualizada"], ["Minha Empresa", "My Company", "Mi Empresa"],
  ["Logo da empresa: PNG ou SVG sem fundo, recomendado 600 × 200 px (proporção 3:1), até 1 MB. Aparece na tela de login (centralizada), no menu, nas etiquetas e nos relatórios em PDF.", "Company logo: PNG or SVG without background, recommended 600 × 200 px (3:1), up to 1 MB. Shown on the login screen, menu, labels and PDF reports.", "Logo de la empresa: PNG o SVG sin fondo, recomendado 600 × 200 px (3:1), hasta 1 MB. Aparece en el inicio de sesión, el menú, las etiquetas y los informes PDF."],
  ["Logo da sua empresa: PNG ou SVG sem fundo, recomendado 600 × 200 px (3:1), até 1 MB. Sai nos orçamentos, etiquetas e relatórios impressos.", "Your company logo: PNG or SVG without background, recommended 600 × 200 px (3:1), up to 1 MB. Printed on quotes, labels and reports.", "Logo de su empresa: PNG o SVG sin fondo, recomendado 600 × 200 px (3:1), hasta 1 MB. Sale en presupuestos, etiquetas e informes."],
  ["Nenhum assinante", "No subscribers", "Sin suscriptores"], ["As contas criadas pelo app aparecerão aqui com o status de pagamento.", "Accounts created in the app will appear here with payment status.", "Las cuentas creadas en la app aparecerán aquí con el estado de pago."],
  ["Excluir assinante", "Delete subscriber", "Eliminar suscriptor"], ["RECEITA", "REVENUE", "INGRESOS"], ["MENSAIS", "MONTHLY", "MENSUALES"], ["VITALÍCIAS", "LIFETIME", "DE POR VIDA"],
  // senha / registro / assinatura
  ["Enviar código", "Send code", "Enviar código"], ["Reenviar código", "Resend code", "Reenviar código"], ["Código (6 dígitos)", "Code (6 digits)", "Código (6 dígitos)"], ["Código enviado", "Code sent", "Código enviado"],
  ["Confirmar nova senha", "Confirm new password", "Confirmar nueva contraseña"], ["mínimo 6 caracteres", "at least 6 characters", "mínimo 6 caracteres"], ["repita a senha", "repeat the password", "repita la contraseña"],
  ["Informe o e-mail da conta.", "Enter the account e-mail.", "Ingrese el correo de la cuenta."], ["Informe o código de 6 dígitos recebido por e-mail.", "Enter the 6-digit code received by e-mail.", "Ingrese el código de 6 dígitos recibido por correo."],
  ["A nova senha deve ter pelo menos 6 caracteres.", "The new password must have at least 6 characters.", "La nueva contraseña debe tener al menos 6 caracteres."], ["As senhas não coincidem.", "Passwords do not match.", "Las contraseñas no coinciden."],
  ["Se o e-mail estiver cadastrado, você receberá um código de 6 dígitos.", "If the e-mail is registered, you will receive a 6-digit code.", "Si el correo está registrado, recibirá un código de 6 dígitos."],
  ["Informe o e-mail da sua conta. Enviaremos um código de 6 dígitos para você criar uma nova senha.", "Enter your account e-mail. We will send a 6-digit code so you can create a new password.", "Ingrese el correo de su cuenta. Enviaremos un código de 6 dígitos para crear una nueva contraseña."],
  ["Senha redefinida", "Password reset", "Contraseña restablecida"], ["Entre com a nova senha.", "Sign in with your new password.", "Ingrese con la nueva contraseña."],
  ["Biometria não reconhecida. Entre com e-mail e senha.", "Biometrics not recognized. Sign in with e-mail and password.", "Biometría no reconocida. Ingrese con correo y contraseña."],
  ["Nome completo", "Full name", "Nombre completo"], ["Nome completo *", "Full name *", "Nombre completo *"], ["Senha * (mín. 6 caracteres)", "Password * (min. 6 characters)", "Contraseña * (mín. 6 caracteres)"],
  ["Endereço completo *", "Full address *", "Dirección completa *"], ["Rua, nº, bairro, cidade - UF, CEP", "Street, no., district, city - state, ZIP", "Calle, nº, barrio, ciudad - prov., CP"],
  ["Dados para o contrato de assinatura", "Subscription contract details", "Datos para el contrato de suscripción"], ["Criar conta e continuar", "Create account and continue", "Crear cuenta y continuar"],
  ["Já tenho conta", "I already have an account", "Ya tengo cuenta"], ["Erro ao registrar", "Registration error", "Error al registrar"],
  ["Preencha nome completo, e-mail, senha, CPF e endereço.", "Fill in full name, e-mail, password, CPF and address.", "Complete nombre completo, correo, contraseña, CPF y dirección."],
  ["Após criar a conta você aceitará o contrato e escolherá o plano: R$ 25,90/mês por usuário ou licença vitalícia por R$ 999,00 (de R$ 1.500,00).", "After creating the account you will accept the contract and choose a plan: R$ 25.90/month per user or lifetime license for R$ 999.00 (from R$ 1,500.00).", "Después de crear la cuenta aceptará el contrato y elegirá el plan: R$ 25,90/mes por usuario o licencia de por vida por R$ 999,00 (antes R$ 1.500,00)."],
  ["Ativação da conta", "Account activation", "Activación de la cuenta"], ["1 · Contrato", "1 · Contract", "1 · Contrato"], ["1 · Contrato aceito", "1 · Contract accepted", "1 · Contrato aceptado"], ["2 · Pagamento", "2 · Payment", "2 · Pago"], ["2 · Pago", "2 · Paid", "2 · Pagado"],
  ["Contrato de assinatura", "Subscription contract", "Contrato de suscripción"], ["Aceitar contrato", "Accept contract", "Aceptar contrato"], ["Marque a caixa de aceite do contrato", "Tick the contract acceptance box", "Marque la casilla de aceptación del contrato"],
  ["Li e aceito o contrato. Serão registrados nome, CPF, data/hora e IP do aceite.", "I have read and accept the contract. Name, CPF, date/time and IP will be recorded.", "Leí y acepto el contrato. Se registrarán nombre, CPF, fecha/hora e IP."],
  ["Escolha o plano", "Choose a plan", "Elija el plan"], ["Assinatura mensal", "Monthly subscription", "Suscripción mensual"], ["Assinar mensal", "Subscribe monthly", "Suscribir mensual"], ["/mês por usuário", "/month per user", "/mes por usuario"],
  ["Renovação automática · cancele quando quiser · bloqueio automático em caso de não pagamento.", "Auto-renewal · cancel anytime · automatic block on non-payment.", "Renovación automática · cancele cuando quiera · bloqueo automático por falta de pago."],
  ["Licença vitalícia ilimitada", "Unlimited lifetime license", "Licencia de por vida ilimitada"], ["Comprar licença vitalícia", "Buy lifetime license", "Comprar licencia de por vida"],
  ["Pagamento único · usuários ilimitados · atualizações por 12 meses e correções sem prazo.", "One-time payment · unlimited users · 12 months of updates and unlimited fixes.", "Pago único · usuarios ilimitados · actualizaciones por 12 meses y correcciones sin plazo."],
  ["Pagamento seguro via Stripe (cartão). O acesso é liberado automaticamente após a confirmação.", "Secure payment via Stripe (card). Access is granted automatically after confirmation.", "Pago seguro vía Stripe (tarjeta). El acceso se libera automáticamente tras la confirmación."],
  ["Já paguei — verificar", "I already paid — check", "Ya pagué — verificar"], ["Erro ao iniciar pagamento", "Error starting payment", "Error al iniciar el pago"], ["Voltar aos planos", "Back to plans", "Volver a los planes"],
  ["Pagamento confirmado!", "Payment confirmed!", "¡Pago confirmado!"], ["Pagamento em processamento", "Payment processing", "Pago en proceso"], ["Pagamento ainda não confirmado", "Payment not yet confirmed", "Pago aún no confirmado"],
  ["Pagamento cancelado", "Payment canceled", "Pago cancelado"], ["Entrar no app", "Enter the app", "Entrar a la app"], ["Sua conta está ativa. Bem-vindo ao InfraManager.", "Your account is active. Welcome to Zatriz.", "Su cuenta está activa. Bienvenido a Zatriz."],
  ["Assim que o Stripe confirmar, seu acesso será liberado automaticamente.", "As soon as Stripe confirms, your access will be granted automatically.", "Cuando Stripe confirme, su acceso se liberará automáticamente."],
  ["Conclua o pagamento e toque em verificar novamente.", "Complete the payment and tap check again.", "Complete el pago y toque verificar de nuevo."],
  ["Nenhuma cobrança foi realizada. Você pode escolher o plano novamente quando quiser.", "No charge was made. You can choose a plan again anytime.", "No se realizó ningún cargo. Puede elegir el plan nuevamente cuando quiera."],
];
