#!/usr/bin/env python3
"""Manual Zatriz em 3 idiomas (pt/en/es), dados fictícios, sem prints reais. Saída: docs/manual-zatriz-{lang}.pdf"""
import os, subprocess, datetime

D = os.path.dirname(os.path.abspath(__file__))

T = {
 "pt": dict(title="Manual do usuário", sub="Gestão de infraestrutura de TI", toc="Sumário", ex="Exemplo", date="Versão 1.0", sections=[
  ("Acesso e conta", "Entre com e-mail e senha. Novos clientes tocam em <b>Criar conta</b>, informam nome completo, CPF, telefone e endereço, aceitam o contrato digital (nome, CPF, data/hora e IP ficam registrados) e escolhem o plano: <b>Mensal R$ 25,90/usuário</b> ou <b>Licença vitalícia R$ 999,00</b> (de R$ 1.500,00). O pagamento é feito pelo Stripe e o acesso é liberado automaticamente. Cada usuário usa apenas <b>um dispositivo por vez</b>. Em Configurações é possível ativar o <b>login por biometria</b>.", "Maria Souza · CPF 123.456.789-00 · plano mensal · 1 celular conectado"),
  ("Painel inicial", "Mostra dispositivos cadastrados, preventivas vencidas e próximas, servidores com instabilidade (toque para abrir o mapa), orçamentos pendentes, gráfico de manutenções dos últimos 6 meses, distribuição por tipo, latência, mapa e topologias. O <b>menu ☰</b> concentra todos os acessos.", "42 dispositivos · 3 preventivas vencidas · 1 servidor instável"),
  ("Dispositivos e etiquetas QR", "Cadastre computadores, notebooks, servidores, tablets, impressoras, celulares e equipamentos de rede com campos específicos por tipo (memória, HD, placa de vídeo, processador...), patrimônio, número de série, setor, foto pela câmera e periodicidade da preventiva. A <b>etiqueta 7,5 × 4,5 cm</b> traz patrimônio, setor, série, configuração, QR Code, logo e data/hora da impressão (compatível com Zebra GT ou A4). Leia o QR pelo app para abrir a ficha e registrar <b>preventivas</b> e <b>corretivas</b> com histórico completo. O painel avisa quando uma preventiva vence.", "PAT-0042 · Notebook Dell Latitude · Setor Financeiro · preventiva a cada 3 meses"),
  ("Orçamentos e clientes", "Crie orçamentos de venda ou serviço com itens, desconto e impostos; acompanhe o status (rascunho, pendente, aprovado, rejeitado, concluído); filtre por código, cliente e período; gere o PDF com a logo da empresa. No cliente informe contato, documento, endereço, <b>estado e cidade</b> e anexe o <b>contrato em PDF</b>.", "ORC-0007 · Empresa Exemplo Ltda · R$ 4.890,00 · aprovado"),
  ("Racks, topologia e plantas", "Monte racks de 6U a 50U com equipamentos desenhados de forma realista (switch, patch panel, servidor, torre, nobreak...) e <b>LEDs</b>: verde piscando = ativo, amarelo = instável, vermelho piscando = offline (vinculando o equipamento a um servidor monitorado). Gere topologias automaticamente e ajuste arrastando e conectando dispositivos. Envie a imagem da planta ou desenhe cômodos e marque pontos de rede, APs e câmeras. Tudo exporta em PDF.", "Rack CPD 42U · SW-CORE-01 (48p) · SRV-FILE-01 vinculado"),
  ("Servidores, mapa e agente", "Cadastre host, porta, estado e cidade (posiciona no mapa do Brasil, colorido por região; cidades aparecem no zoom). <b>Verificar</b> testa a conexão e mede a latência. Instale o <b>agente</b> (Linux/Windows, script gerado no app) para receber CPU, memória e disco a cada 5 min. Firewall: saída TCP 443 para o app; entrada na porta cadastrada para o teste externo. Dados de acesso ficam mascarados (toque para revelar).", "SRV-ERP · Campinas/SP · 38 ms · CPU 22% · RAM 61%"),
  ("Alertas por e-mail", "Em Configurações informe servidor SMTP, porta (587 TLS / 465 SSL), usuário, senha e e-mail de destino. O app envia alerta quando um servidor ficar offline e um resumo diário das preventivas vencidas ou vencendo em 15 dias. Use <b>Enviar teste</b> para validar.", "smtp.gmail.com · 587 · alertas@empresa.com"),
  ("Configurações e administração", "Tema escuro/claro, idioma (Português, Inglês, Espanhol), logo da empresa (PNG/SVG sem fundo, 600 × 200 px), imagem da tela de login, links de tutorial (PDF e vídeo) e <b>usuário operador</b> (1 por licença: cadastra e edita, não exclui). O administrador vê em <b>Assinantes</b> quem comprou, quem pagou, receita, e pode aprovar 30 dias de teste ou bloquear.", "Assinantes: 18 contas · 15 ativas · R$ 2.997,00 recebidos"),
 ]),
 "en": dict(title="User manual", sub="IT infrastructure management", toc="Contents", ex="Example", date="Version 1.0", sections=[
  ("Access and account", "Sign in with e-mail and password. New customers tap <b>Create account</b>, enter full name, tax ID, phone and address, accept the digital contract (name, ID, date/time and IP are recorded) and choose a plan: <b>Monthly R$ 25.90/user</b> or <b>Lifetime license R$ 999.00</b>. Payment goes through Stripe and access is granted automatically. Each user can be signed in on <b>one device at a time</b>. Biometric login can be enabled in Settings.", "Maria Souza · monthly plan · 1 phone connected"),
  ("Dashboard", "Shows registered devices, overdue/upcoming preventive maintenance, unstable servers (tap to open the map), pending quotes, a 6-month maintenance chart, devices by type, latency, the map and topologies. The <b>☰ menu</b> gathers every area.", "42 devices · 3 overdue · 1 unstable server"),
  ("Devices and QR labels", "Register computers, laptops, servers, tablets, printers, phones and network gear with type-specific fields (memory, storage, GPU, CPU...), asset tag, serial number, department, camera photo and preventive interval. The <b>7.5 × 4.5 cm label</b> carries asset tag, department, serial, configuration, QR Code, logo and print date/time (Zebra GT or A4). Scan the QR in the app to open the record and log <b>preventive</b> and <b>corrective</b> maintenance with full history. The dashboard warns when preventive maintenance is due.", "PAT-0042 · Dell Latitude laptop · Finance · every 3 months"),
  ("Quotes and clients", "Create sales or service quotes with items, discount and taxes; track status; filter by code, client and date range; export a PDF with your logo. Client records include contact, tax ID, address, <b>state and city</b> and an attached <b>contract PDF</b>.", "QUO-0007 · Example Company · R$ 4,890.00 · approved"),
  ("Racks, topology and floor plans", "Build 6U–50U racks with realistic equipment faces (switch, patch panel, server, tower, UPS...) and <b>LEDs</b>: blinking green = active, yellow = unstable, blinking red = offline (link the item to a monitored server). Auto-generate topologies and adjust by dragging and connecting devices. Upload a floor plan image or draw rooms and place network points, APs and cameras. Everything exports to PDF.", "Rack DC 42U · SW-CORE-01 (48p) · SRV-FILE-01 linked"),
  ("Servers, map and agent", "Register host, port, state and city (placed on the Brazil map, colored by region; cities appear on zoom). <b>Check</b> tests the connection and measures latency. Install the <b>agent</b> (Linux/Windows script generated in the app) to receive CPU, memory and disk every 5 minutes. Firewall: outbound TCP 443 to the app; inbound on the registered port for the external check. Access data is masked (tap to reveal).", "SRV-ERP · Campinas/SP · 38 ms · CPU 22% · RAM 61%"),
  ("E-mail alerts", "In Settings enter SMTP server, port (587 TLS / 465 SSL), user, password and destination e-mail. The app e-mails you when a server goes offline and sends a daily digest of overdue/upcoming preventive maintenance. Use <b>Send test</b> to validate.", "smtp.gmail.com · 587 · alerts@company.com"),
  ("Settings and administration", "Dark/light theme, language (Portuguese, English, Spanish), company logo (PNG/SVG, 600 × 200 px), login screen image, tutorial links (PDF and video) and one <b>operator user</b> per license (can create and edit, cannot delete). The administrator sees in <b>Subscribers</b> who bought, who paid, revenue, and can approve a 30-day trial or block accounts.", "Subscribers: 18 accounts · 15 active · R$ 2,997.00 received"),
 ]),
 "es": dict(title="Manual del usuario", sub="Gestión de infraestructura de TI", toc="Índice", ex="Ejemplo", date="Versión 1.0", sections=[
  ("Acceso y cuenta", "Ingrese con correo y contraseña. Los nuevos clientes tocan <b>Crear cuenta</b>, informan nombre completo, documento, teléfono y dirección, aceptan el contrato digital (nombre, documento, fecha/hora e IP quedan registrados) y eligen el plan: <b>Mensual R$ 25,90/usuario</b> o <b>Licencia de por vida R$ 999,00</b>. El pago se realiza por Stripe y el acceso se libera automáticamente. Cada usuario usa <b>un dispositivo a la vez</b>. En Configuración puede activar el inicio por biometría.", "Maria Souza · plan mensual · 1 celular conectado"),
  ("Panel inicial", "Muestra dispositivos registrados, preventivos vencidos y próximos, servidores inestables (toque para abrir el mapa), presupuestos pendientes, gráfico de mantenimientos de 6 meses, distribución por tipo, latencia, mapa y topologías. El <b>menú ☰</b> concentra todos los accesos.", "42 dispositivos · 3 vencidos · 1 servidor inestable"),
  ("Dispositivos y etiquetas QR", "Registre computadoras, notebooks, servidores, tablets, impresoras, celulares y equipos de red con campos por tipo (memoria, disco, video, procesador...), patrimonio, número de serie, sector, foto con la cámara y periodicidad del preventivo. La <b>etiqueta de 7,5 × 4,5 cm</b> incluye patrimonio, sector, serie, configuración, código QR, logo y fecha/hora de impresión (Zebra GT o A4). Lea el QR con la app para abrir la ficha y registrar <b>preventivos</b> y <b>correctivos</b> con historial. El panel avisa cuando vence un preventivo.", "PAT-0042 · Notebook Dell Latitude · Finanzas · cada 3 meses"),
  ("Presupuestos y clientes", "Cree presupuestos de venta o servicio con ítems, descuento e impuestos; siga el estado; filtre por código, cliente y período; exporte el PDF con su logo. En el cliente registre contacto, documento, dirección, <b>estado y ciudad</b> y adjunte el <b>contrato en PDF</b>.", "PRE-0007 · Empresa Ejemplo · R$ 4.890,00 · aprobado"),
  ("Racks, topología y planos", "Arme racks de 6U a 50U con equipos dibujados de forma realista (switch, patch panel, servidor, torre, UPS...) y <b>LEDs</b>: verde parpadeando = activo, amarillo = inestable, rojo parpadeando = fuera de línea (vinculando el equipo a un servidor monitoreado). Genere topologías automáticamente y ajústelas arrastrando y conectando. Suba la imagen del plano o dibuje ambientes y marque puntos de red, APs y cámaras. Todo se exporta a PDF.", "Rack CPD 42U · SW-CORE-01 (48p) · SRV-FILE-01 vinculado"),
  ("Servidores, mapa y agente", "Registre host, puerto, estado y ciudad (se ubica en el mapa de Brasil, coloreado por región; las ciudades aparecen al hacer zoom). <b>Verificar</b> prueba la conexión y mide la latencia. Instale el <b>agente</b> (script Linux/Windows generado en la app) para recibir CPU, memoria y disco cada 5 min. Firewall: salida TCP 443 hacia la app; entrada en el puerto registrado para la prueba externa. Los datos de acceso están enmascarados (toque para revelar).", "SRV-ERP · Campinas/SP · 38 ms · CPU 22% · RAM 61%"),
  ("Alertas por correo", "En Configuración informe servidor SMTP, puerto (587 TLS / 465 SSL), usuario, contraseña y correo de destino. La app envía alerta cuando un servidor queda fuera de línea y un resumen diario de preventivos vencidos o por vencer en 15 días. Use <b>Enviar prueba</b> para validar.", "smtp.gmail.com · 587 · alertas@empresa.com"),
  ("Configuración y administración", "Tema oscuro/claro, idioma (portugués, inglés, español), logo de la empresa (PNG/SVG, 600 × 200 px), imagen de la pantalla de inicio, enlaces de tutorial (PDF y video) y un <b>usuario operador</b> por licencia (crea y edita, no elimina). El administrador ve en <b>Suscriptores</b> quién compró, quién pagó, ingresos, y puede aprobar 30 días de prueba o bloquear.", "Suscriptores: 18 cuentas · 15 activas · R$ 2.997,00 recibidos"),
 ]),
}

CSS = """@page{size:A5;margin:14mm 12mm}body{font-family:Helvetica,Arial,sans-serif;color:#141833;font-size:10.5px;line-height:1.5}
.cover{height:170mm;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;background:linear-gradient(160deg,#0B0D1F,#1E3A8A 60%,#2DD4F5);color:#fff;border-radius:14px;padding:20px;page-break-after:always}
.cover h1{font-size:44px;margin:0;letter-spacing:6px}.cover p{margin:4px;opacity:.9}
h2{font-size:15px;color:#1E6FE8;margin:0 0 6px;display:flex;align-items:center;gap:8px}
.n{display:inline-flex;width:24px;height:24px;border-radius:12px;background:#1E6FE8;color:#fff;align-items:center;justify-content:center;font-size:12px}
section{page-break-inside:avoid;margin-bottom:14px;padding:12px;border:1px solid #E1E5F5;border-radius:12px;background:#fff}
.ex{margin-top:8px;padding:8px 10px;background:#F0F5FF;border-left:3px solid #2DD4F5;border-radius:6px;font-size:9.5px;color:#334}
.toc{page-break-after:always}.toc li{margin:4px 0}"""

for lang, t in T.items():
    secs = "".join(f'<section><h2><span class="n">{i+1}</span>{h}</h2><p>{p}</p><div class="ex"><b>{t["ex"]}:</b> {ex}</div></section>' for i, (h, p, ex) in enumerate(t["sections"]))
    toc = "".join(f"<li>{h}</li>" for h, _, _ in t["sections"])
    html = f'<html><head><meta charset="utf-8"/><style>{CSS}</style></head><body><div class="cover"><h1>ZATRIZ</h1><p style="font-size:16px;letter-spacing:2px">{t["title"].upper()}</p><p>{t["sub"]}</p><p style="font-size:9px;margin-top:20px">{t["date"]} · {datetime.date.today().strftime("%d/%m/%Y")}</p></div><div class="toc"><h2>{t["toc"]}</h2><ol>{toc}</ol></div>{secs}</body></html>'
    hp = os.path.join(D, f"manual-zatriz-{lang}.html"); open(hp, "w", encoding="utf-8").write(html)
    pdf = os.path.join(D, f"manual-zatriz-{lang}.pdf")
    subprocess.run(["google-chrome", "--headless=new", "--no-sandbox", "--disable-gpu", f"--print-to-pdf={pdf}", "--no-pdf-header-footer", "file://" + hp], capture_output=True, timeout=120)
    print(pdf, os.path.getsize(pdf) if os.path.exists(pdf) else "FAILED")
